"""
SOC 2 / ISO Audit Log Export — Weekly Cron + Email Pipeline
============================================================
Once a week (Monday 00:00 UTC by default) the scheduler:
  1. Walks the past 7 days of `audit_logs`
  2. Builds the same tamper-evident hash-chain bundle used by the
     interactive admin export (`audit_export_routes`)
  3. Anchors the root hash on Hedera HCS (best-effort)
  4. Persists the export in `audit_log_exports` so the file is downloadable
     from the admin "History" panel
  5. Emails the compliance officer with the export id, root hash, Hedera
     anchor info and a deep link to download the ZIP

Environment knobs:
  • SOC2_CRON_INTERVAL_HOURS — default 168 (weekly)
  • SOC2_CRON_INITIAL_DELAY_SECS — default 300 (5 min after boot)
  • SOC2_COMPLIANCE_OFFICER_EMAIL — default mrclay925@gmail.com
  • SOC2_PUBLIC_DOWNLOAD_BASE — defaults to BACKEND_URL value used by the
                                 emailed link
"""
from __future__ import annotations
import asyncio
import csv
import hashlib
import io
import json
import logging
import os
import uuid
import zipfile
from datetime import datetime, timezone, timedelta
from typing import Optional

logger = logging.getLogger(__name__)

_db = None
_started = False


def set_db(database):
    global _db
    _db = database


def _canonical_json(obj) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), default=str)


def _build_zip(rows: list, export_id: str, generated_at: str, generated_by: str,
               root_hash: str, hcs_result: Optional[dict],
               hedera_tx_id: Optional[str], hedera_topic: Optional[str],
               hedera_network: Optional[str], start_date: str, end_date: str) -> bytes:
    """Identical layout to /api/admin/audit-export/generate — keeps verifier
    code from a single trusted format."""
    csv_buf = io.StringIO()
    cols = ["#", "id", "timestamp", "user_email", "action", "resource_type",
            "resource_id", "severity", "description", "ip_address",
            "prev_hash", "row_hash"]
    w = csv.writer(csv_buf)
    w.writerow(cols)
    for i, r in enumerate(rows, start=1):
        w.writerow([
            i, r.get("id", ""), r.get("timestamp", ""),
            r.get("user_email", "system"), r.get("action", ""),
            r.get("resource_type", ""), r.get("resource_id", ""),
            r.get("severity", "info"),
            (r.get("description") or "")[:240],
            r.get("ip_address", ""),
            r.get("prev_hash", ""), r.get("row_hash", ""),
        ])
    csv_bytes = csv_buf.getvalue().encode("utf-8")

    json_doc = {
        "export_id": export_id,
        "generated_at": generated_at,
        "generated_by": generated_by,
        "row_count": len(rows),
        "root_hash": root_hash,
        "genesis_hash": "0" * 64,
        "hash_algorithm": "sha256",
        "chain_algorithm": "row_hash = sha256(prev_hash || canonical_json(row_without_hash_fields))",
        "hedera_anchor": {
            "submitted": bool(hcs_result and hcs_result.get("success")),
            "network": hedera_network,
            "topic_id": hedera_topic,
            "transaction_id": hedera_tx_id,
            "sequence_number": (hcs_result or {}).get("sequence_number") if hcs_result else None,
            "explorer_url": (hcs_result or {}).get("explorer_url") if hcs_result else None,
        },
        "filters": {"start_date": start_date, "end_date": end_date},
        "rows": rows,
    }
    json_bytes = json.dumps(json_doc, indent=2, default=str).encode("utf-8")

    txt = io.StringIO()
    txt.write("NotaryChain — Weekly SOC 2 / ISO 27001 Audit Log Export\n")
    txt.write("=" * 60 + "\n")
    txt.write(f"Export ID:        {export_id}\n")
    txt.write(f"Generated at:     {generated_at}\n")
    txt.write(f"Generated by:     {generated_by}\n")
    txt.write(f"Row count:        {len(rows)}\n")
    txt.write(f"Window:           {start_date} → {end_date}\n")
    txt.write(f"Root hash:        {root_hash}\n")
    if hedera_tx_id:
        txt.write(f"\nHedera anchor:\n  Network: {hedera_network}\n  Topic: {hedera_topic}\n  Tx: {hedera_tx_id}\n")
    else:
        txt.write("\nHedera anchor: not submitted (offline)\n")
    txt.write("\nVerification: see /api/admin/audit-export/generate documentation.\n")
    manifest_bytes = txt.getvalue().encode("utf-8")

    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("audit_log.csv", csv_bytes)
        zf.writestr("audit_log.json", json_bytes)
        zf.writestr("MANIFEST.txt", manifest_bytes)
    return zip_buf.getvalue()


async def run_weekly_export() -> Optional[dict]:
    """Single-shot weekly export. Idempotent — multiple calls in the same week
    just produce additional dated bundles (each with its own export_id)."""
    if _db is None:
        logger.warning("[SOC2.cron] _db not configured; skipping export")
        return None

    end = datetime.now(timezone.utc)
    start = end - timedelta(days=7)
    start_str = start.strftime("%Y-%m-%d")
    end_str = end.strftime("%Y-%m-%d")

    cursor = _db.audit_logs.find(
        {"timestamp": {"$gte": start.isoformat(), "$lte": end.isoformat()}},
        {"_id": 0},
    ).sort("timestamp", 1)

    rows: list = []
    prev_hash = "0" * 64
    async for row in cursor:
        row.pop("password", None)
        payload = {k: v for k, v in row.items() if k not in ("prev_hash", "row_hash")}
        row_hash = hashlib.sha256((prev_hash + _canonical_json(payload)).encode()).hexdigest()
        row["prev_hash"] = prev_hash
        row["row_hash"] = row_hash
        rows.append(row)
        prev_hash = row_hash

    if not rows:
        logger.info("[SOC2.cron] No audit rows in the last 7 days — skipping export.")
        return None

    export_id = "AUDIT-WEEKLY-" + end.strftime("%Y%m%d") + "-" + uuid.uuid4().hex[:6].upper()
    root_hash = rows[-1]["row_hash"]
    generated_at = end.isoformat()
    officer = os.environ.get("SOC2_COMPLIANCE_OFFICER_EMAIL") or "mrclay925@gmail.com"

    # Hedera anchor (best-effort)
    hcs_result = None
    hedera_tx_id = None
    hedera_topic = None
    hedera_network = None
    try:
        from services.hedera_service import hedera_service
        hcs_result = await hedera_service.submit_message(
            hedera_service.default_topic_id,
            {
                "type": "AUDIT_LOG_EXPORT_ANCHOR",
                "export_id": export_id,
                "root_hash": root_hash,
                "row_count": len(rows),
                "generated_at": generated_at,
                "generated_by": "weekly-cron",
                "filters": {"start_date": start_str, "end_date": end_str},
            },
        )
        if hcs_result and hcs_result.get("success"):
            hedera_tx_id = f"{hedera_service.account_id}@{int(end.timestamp())}"
            hedera_topic = hedera_service.default_topic_id
            hedera_network = hedera_service.network
    except Exception as e:
        logger.warning("[SOC2.cron] Hedera anchor failed: %s", e)

    zip_bytes = _build_zip(rows, export_id, generated_at, "weekly-cron",
                           root_hash, hcs_result, hedera_tx_id, hedera_topic,
                           hedera_network, start_str, end_str)

    # Persist export record so the admin "History" panel + the emailed download
    # link both have a place to read from.
    await _db.audit_log_exports.insert_one({
        "id": uuid.uuid4().hex,
        "export_id": export_id,
        "generated_at": generated_at,
        "generated_by": "weekly-cron",
        "row_count": len(rows),
        "root_hash": root_hash,
        "hedera_tx_id": hedera_tx_id,
        "hedera_topic": hedera_topic,
        "hedera_network": hedera_network,
        "filters": {"start_date": start_str, "end_date": end_str},
        "size_bytes": len(zip_bytes),
        "scheduled": True,
        "email_sent_to": officer,
        # Keep the ZIP bytes so the email link can resolve it without
        # re-walking the audit_logs.
        "zip_b64": __import__("base64").b64encode(zip_bytes).decode(),
    })

    # Send email (Resend) with the export attached + a link
    try:
        from services.email_service import EmailService
        download_url = f"/api/admin/audit-export/scheduled/{export_id}/download"
        html = _build_email_html(export_id, generated_at, len(rows), start_str, end_str,
                                  root_hash, hedera_tx_id, hedera_topic, download_url)
        await EmailService.send_email(officer,
            subject=f"[NotaryChain SOC2] Weekly audit export — {len(rows)} rows · {end_str}",
            html_content=html)
        logger.info("[SOC2.cron] Weekly export %s emailed to %s", export_id, officer)
    except Exception as e:
        logger.warning("[SOC2.cron] Email dispatch failed: %s", e)

    # Self-log
    try:
        await _db.audit_logs.insert_one({
            "id": uuid.uuid4().hex,
            "user_email": "system@notarychain",
            "action": "audit_log_export_scheduled",
            "resource_type": "audit_log",
            "description": f"Weekly SOC2 export {export_id} — {len(rows)} rows, emailed to {officer}",
            "details": {"export_id": export_id, "row_count": len(rows),
                        "root_hash": root_hash, "hedera_tx_id": hedera_tx_id},
            "severity": "info",
            "timestamp": generated_at,
        })
    except Exception:
        pass

    return {"export_id": export_id, "row_count": len(rows), "root_hash": root_hash,
            "email_sent_to": officer}


def _build_email_html(export_id: str, generated_at: str, row_count: int,
                      start: str, end: str, root_hash: str,
                      hedera_tx_id: Optional[str], hedera_topic: Optional[str],
                      download_url: str) -> str:
    backend_base = (os.environ.get("BACKEND_PUBLIC_URL") or "").rstrip("/")
    full_link = f"{backend_base}{download_url}" if backend_base else download_url
    return f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;background:#f6f5ee;padding:24px;color:#0f1825">
      <div style="max-width:560px;margin:0 auto;background:#fff;border-radius:12px;border:1px solid #e5e7eb;overflow:hidden">
        <div style="background:#0f1825;color:#fff;padding:18px 22px">
          <p style="margin:0;font-size:11px;letter-spacing:2.5px;text-transform:uppercase;color:#fb923c;font-weight:700">NotaryChain · SOC 2 Evidence</p>
          <h1 style="margin:6px 0 0;font-size:22px;font-weight:700">Weekly audit log export ready</h1>
        </div>
        <div style="padding:22px">
          <p style="margin:0 0 12px;font-size:14px;line-height:22px">
            Hi compliance officer — your weekly tamper-evident audit log export has been generated and anchored on Hedera HCS.
          </p>
          <table style="font-size:13px;border-collapse:collapse;width:100%;margin:14px 0;">
            <tr><td style="padding:6px 10px;color:#6b7280;width:40%">Export ID</td><td style="padding:6px 10px;font-family:Menlo,monospace;color:#0f1825">{export_id}</td></tr>
            <tr><td style="padding:6px 10px;color:#6b7280">Window</td><td style="padding:6px 10px;color:#0f1825">{start} → {end}</td></tr>
            <tr><td style="padding:6px 10px;color:#6b7280">Rows</td><td style="padding:6px 10px;color:#0f1825"><b>{row_count}</b></td></tr>
            <tr><td style="padding:6px 10px;color:#6b7280">Root hash</td><td style="padding:6px 10px;font-family:Menlo,monospace;font-size:11px;color:#0f1825;word-break:break-all">{root_hash}</td></tr>
            <tr><td style="padding:6px 10px;color:#6b7280">Generated</td><td style="padding:6px 10px;color:#0f1825">{generated_at}</td></tr>
            {f'<tr><td style="padding:6px 10px;color:#6b7280">Hedera Tx</td><td style="padding:6px 10px;font-family:Menlo,monospace;font-size:11px;color:#10b981">{hedera_tx_id}</td></tr>' if hedera_tx_id else ''}
            {f'<tr><td style="padding:6px 10px;color:#6b7280">Topic</td><td style="padding:6px 10px;font-family:Menlo,monospace;color:#0f1825">{hedera_topic}</td></tr>' if hedera_topic else ''}
          </table>
          <a href="{full_link}" style="display:inline-block;background:#fb923c;color:#fff;text-decoration:none;padding:11px 22px;border-radius:6px;font-weight:700;font-size:14px;margin:6px 0">Download Evidence ZIP</a>
          <p style="font-size:11px;color:#6b7280;margin:14px 0 0">
            This evidence packet is tamper-evident (SHA-256 hash chain) and Hedera-anchored.
            Verification instructions are in the MANIFEST.txt inside the ZIP.
          </p>
        </div>
      </div>
      <p style="text-align:center;margin:14px 0 0;font-size:11px;color:#9ca3af">NotaryChain — Automated SOC 2 / ISO 27001 Compliance Pipeline</p>
    </div>
    """


async def run_scheduler():
    """Background coroutine — every minute, fires any scheduled_export_configs
    whose `next_run` is due. Also keeps the legacy single-tenant weekly export
    alive for users who haven't created a config yet."""
    global _started
    if _started:
        return
    _started = True
    initial = int(os.environ.get("SOC2_CRON_INITIAL_DELAY_SECS") or 300)
    logger.info("[SOC2.cron] Multi-tenant scheduler started · initial=%ss · tick=60s", initial)
    await asyncio.sleep(initial)

    # First-boot fallback: if no configs exist, run the legacy weekly once
    try:
        if _db is not None and await _db.scheduled_export_configs.count_documents({}) == 0:
            await run_weekly_export()
    except Exception as e:
        logger.warning("[SOC2.cron] First-boot fallback failed: %s", e)

    while True:
        try:
            await _tick_scheduled_configs()
        except Exception as e:
            logger.error("[SOC2.cron] Tick failed: %s", e)
        await asyncio.sleep(60)  # check every minute


async def _tick_scheduled_configs():
    if _db is None:
        return
    now = datetime.now(timezone.utc)
    cursor = _db.scheduled_export_configs.find(
        {"enabled": True, "next_run": {"$lte": now.isoformat()}},
        {"_id": 0},
    )
    async for cfg in cursor:
        try:
            await run_for_config(cfg)
        except Exception as e:
            logger.error("[SOC2.cron] config %s failed: %s", cfg.get("id"), e)


async def run_for_config(cfg: dict) -> Optional[dict]:
    """Generates an export bundle scoped to a single config + emails every
    recipient. Returns {export_id, row_count, root_hash, sent_to[]} or None
    if there were zero matching rows in the cadence window."""
    if _db is None:
        return None
    cadence_hours = int(cfg.get("cadence_hours") or 168)
    end = datetime.now(timezone.utc)
    start = end - timedelta(hours=cadence_hours)
    start_str = start.strftime("%Y-%m-%d")
    end_str = end.strftime("%Y-%m-%d")

    # Build the query — config filters override window for severity/actor/action
    query: dict = {"timestamp": {"$gte": start.isoformat(), "$lte": end.isoformat()}}
    filters = cfg.get("filters") or {}
    if filters.get("actor"):
        query["user_email"] = {"$regex": filters["actor"], "$options": "i"}
    if filters.get("action"):
        query["action"] = {"$regex": filters["action"], "$options": "i"}
    if filters.get("severity"):
        query["severity"] = filters["severity"]

    rows: list = []
    prev_hash = "0" * 64
    async for row in _db.audit_logs.find(query, {"_id": 0}).sort("timestamp", 1):
        row.pop("password", None)
        payload = {k: v for k, v in row.items() if k not in ("prev_hash", "row_hash")}
        row_hash = hashlib.sha256((prev_hash + _canonical_json(payload)).encode()).hexdigest()
        row["prev_hash"] = prev_hash
        row["row_hash"] = row_hash
        rows.append(row)
        prev_hash = row_hash

    next_run = (end + timedelta(hours=cadence_hours)).isoformat()
    if not rows:
        # Bump the next_run anyway so the cron doesn't tight-loop
        await _db.scheduled_export_configs.update_one(
            {"id": cfg["id"]}, {"$set": {"last_run": end.isoformat(), "next_run": next_run}}
        )
        return None

    export_id = f"AUDIT-CFG-{cfg.get('id', '')[:8].upper()}-{end.strftime('%Y%m%d%H%M%S')}-{uuid.uuid4().hex[:4].upper()}"
    root_hash = rows[-1]["row_hash"]
    generated_at = end.isoformat()

    # Hedera anchor (best-effort)
    hcs_result = None
    hedera_tx_id = None
    hedera_topic = None
    hedera_network = None
    try:
        from services.hedera_service import hedera_service
        hcs_result = await hedera_service.submit_message(
            hedera_service.default_topic_id,
            {"type": "AUDIT_LOG_EXPORT_ANCHOR", "config_id": cfg.get("id"),
             "export_id": export_id, "root_hash": root_hash,
             "row_count": len(rows), "generated_at": generated_at,
             "generated_by": "scheduled-cron"},
        )
        if hcs_result and hcs_result.get("success"):
            hedera_tx_id = f"{hedera_service.account_id}@{int(end.timestamp())}"
            hedera_topic = hedera_service.default_topic_id
            hedera_network = hedera_service.network
    except Exception as e:
        logger.warning("[SOC2.cron] Hedera anchor failed: %s", e)

    zip_bytes = _build_zip(rows, export_id, generated_at, f"scheduled:{cfg.get('name')}",
                           root_hash, hcs_result, hedera_tx_id, hedera_topic,
                           hedera_network, start_str, end_str)

    await _db.audit_log_exports.insert_one({
        "id": uuid.uuid4().hex,
        "export_id": export_id,
        "generated_at": generated_at,
        "generated_by": f"scheduled:{cfg.get('name')}",
        "row_count": len(rows),
        "root_hash": root_hash,
        "hedera_tx_id": hedera_tx_id,
        "hedera_topic": hedera_topic,
        "hedera_network": hedera_network,
        "filters": {"start_date": start_str, "end_date": end_str, **filters},
        "size_bytes": len(zip_bytes),
        "scheduled": True,
        "config_id": cfg.get("id"),
        "email_sent_to": ", ".join(cfg.get("recipients", [])),
        "zip_b64": __import__("base64").b64encode(zip_bytes).decode(),
    })

    # Email every recipient
    sent_to: list[str] = []
    try:
        from services.email_service import EmailService
        download_url = f"/api/admin/audit-export/scheduled/{export_id}/download"
        html = _build_email_html(export_id, generated_at, len(rows), start_str, end_str,
                                  root_hash, hedera_tx_id, hedera_topic, download_url)
        subject = f"[NotaryChain SOC2] '{cfg.get('name')}' export — {len(rows)} rows · {end_str}"
        for r in cfg.get("recipients", []):
            try:
                await EmailService.send_email(r, subject=subject, html_content=html)
                sent_to.append(r)
            except Exception as e:
                logger.warning("[SOC2.cron] email to %s failed: %s", r, e)
    except Exception as e:
        logger.warning("[SOC2.cron] EmailService unavailable: %s", e)

    # Update config bookkeeping
    await _db.scheduled_export_configs.update_one(
        {"id": cfg["id"]},
        {"$set": {"last_run": generated_at, "last_export_id": export_id, "next_run": next_run}},
    )

    return {"export_id": export_id, "row_count": len(rows), "root_hash": root_hash, "sent_to": sent_to}
