"""
Batch Certificate Generation
Allows admins to bundle multiple ceremony certificates into a single ZIP
containing:
  - One PDF per ceremony (the existing per-ceremony cert)
  - manifest.csv with metadata + sha256 hash of each PDF
  - combined_certificates.pdf with a cover page + every cert appended
"""
from fastapi import APIRouter, HTTPException, Depends, Body
from fastapi.responses import Response
from datetime import datetime, timezone
from typing import List
import base64
import hashlib
import io
import csv
import zipfile
import logging

from models import User
from routes.auth_routes import get_current_user

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/admin/batch-certificates", tags=["batch-certificates"])

db = None


def set_db(database):
    global db
    db = database


async def _check_admin(current_user: User):
    user_doc = await db.users.find_one({"email": current_user.email})
    if not user_doc or user_doc.get("role") != "admin":
        raise HTTPException(status_code=403, detail="Admin access required")


@router.get("/eligible")
async def list_eligible_ceremonies(current_user: User = Depends(get_current_user)):
    """List sealed ceremonies that are eligible for batch certificate generation."""
    await _check_admin(current_user)
    cursor = db.ceremonies.find(
        {"status": "sealed"},
        {"_id": 0, "ceremony_id": 1, "document_name": 1, "signer_name": 1,
         "initiated_by": 1, "created_at": 1, "has_certificate": 1,
         "consensus.result": 1, "blockchain_seal.transaction_id": 1},
    ).sort("created_at", -1).limit(500)
    items = []
    async for c in cursor:
        items.append({
            "ceremony_id": c.get("ceremony_id"),
            "document_name": c.get("document_name", "Untitled"),
            "signer_name": c.get("signer_name", ""),
            "initiated_by": c.get("initiated_by", ""),
            "created_at": c.get("created_at", ""),
            "has_certificate": bool(c.get("has_certificate")),
            "consensus_result": (c.get("consensus") or {}).get("result", ""),
            "hedera_tx": (c.get("blockchain_seal") or {}).get("transaction_id"),
        })
    return {"ceremonies": items, "total": len(items)}


def _build_cover_pdf(items: list, batch_id: str, generated_by: str) -> bytes:
    """A simple cover PDF describing the batch."""
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    brand_dark = colors.HexColor("#0f1825")
    brand_blue = colors.HexColor("#3b82f6")
    brand_gray = colors.HexColor("#6b7280")

    title_style = ParagraphStyle("CT", parent=styles["Title"], fontSize=24, textColor=brand_dark,
                                 alignment=TA_CENTER, spaceAfter=6, fontName="Helvetica-Bold")
    sub = ParagraphStyle("CS", parent=styles["Normal"], fontSize=11, textColor=brand_gray,
                         alignment=TA_CENTER, spaceAfter=18)
    body = ParagraphStyle("CB", parent=styles["Normal"], fontSize=10, textColor=brand_dark,
                          spaceAfter=6, leading=14)

    elements = []
    elements.append(Paragraph("NOTARYCHAIN", ParagraphStyle("Brand", parent=styles["Normal"],
                              fontSize=11, textColor=brand_blue, alignment=TA_CENTER,
                              fontName="Helvetica-Bold", spaceAfter=4)))
    elements.append(Paragraph("BATCH CERTIFICATE BUNDLE", title_style))
    elements.append(Paragraph(f"Batch ID: {batch_id}", sub))
    elements.append(HRFlowable(width="100%", thickness=1.5, color=brand_blue, spaceAfter=14))

    meta = [
        ["Generated:", datetime.now(timezone.utc).strftime("%B %d, %Y at %H:%M UTC")],
        ["Generated by:", generated_by],
        ["Certificates in bundle:", str(len(items))],
    ]
    t = Table(meta, colWidths=[2.0 * inch, 4.5 * inch])
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), brand_gray),
        ("TEXTCOLOR", (1, 0), (1, -1), brand_dark),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 16))

    elements.append(Paragraph("Manifest", ParagraphStyle("H2", parent=styles["Heading2"], fontSize=13,
                              textColor=brand_dark, fontName="Helvetica-Bold", spaceAfter=6)))

    header = ["#", "Ceremony ID", "Document", "Signer", "Sealed"]
    rows = [header]
    for i, it in enumerate(items, start=1):
        rows.append([
            str(i),
            (it["ceremony_id"] or "")[:18],
            (it["document_name"] or "")[:32],
            (it["signer_name"] or "")[:24],
            (it["created_at"] or "")[:10],
        ])
    tbl = Table(rows, colWidths=[0.3 * inch, 1.6 * inch, 2.4 * inch, 1.6 * inch, 0.9 * inch])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), brand_dark),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#e5e7eb")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    elements.append(tbl)
    elements.append(Spacer(1, 12))
    elements.append(Paragraph(
        "This bundle was assembled by NotaryChain's batch generator. Each individual PDF is "
        "self-contained and independently verifiable via the QR code embedded inside it.",
        body))

    doc.build(elements)
    return buf.getvalue()


async def _ensure_certificate(ceremony_id: str) -> dict | None:
    """Returns the certificate doc for a ceremony, generating if missing."""
    cert = await db.ceremony_certificates.find_one({"ceremony_id": ceremony_id}, {"_id": 0})
    if cert:
        return cert
    ceremony = await db.ceremonies.find_one({"ceremony_id": ceremony_id}, {"_id": 0})
    if not ceremony or ceremony.get("status") != "sealed":
        return None
    from services.ceremony_certificate import generate_ceremony_certificate
    try:
        from services import sovereign_id_service
        sovereign_seal = await sovereign_id_service.resolve_seal_for_ceremony(db, ceremony)
    except Exception:
        sovereign_seal = None
    pdf_bytes = generate_ceremony_certificate(ceremony, sovereign_seal=sovereign_seal)
    pdf_b64 = base64.b64encode(pdf_bytes).decode()
    doc = {
        "ceremony_id": ceremony_id,
        "pdf_base64": pdf_b64,
        "size_bytes": len(pdf_bytes),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
    await db.ceremony_certificates.update_one(
        {"ceremony_id": ceremony_id}, {"$set": doc}, upsert=True
    )
    await db.ceremonies.update_one({"ceremony_id": ceremony_id}, {"$set": {"has_certificate": True}})
    return doc


def _safe_filename(s: str) -> str:
    return "".join(c if c.isalnum() or c in ("-", "_") else "_" for c in (s or "ceremony"))[:48]


@router.post("/generate")
async def generate_batch(
    ceremony_ids: List[str] = Body(..., embed=True),
    current_user: User = Depends(get_current_user),
):
    """Build a ZIP bundle for the given ceremony IDs.

    Returns a streamed ZIP that contains:
      - certificates/<doc>_<ceremony_id>.pdf — per-ceremony certificate
      - combined_certificates.pdf            — cover page + all certs merged
      - manifest.csv                         — id, document, signer, date, sha256
      - MANIFEST.txt                         — human-readable summary
    """
    await _check_admin(current_user)

    if not ceremony_ids:
        raise HTTPException(status_code=400, detail="At least one ceremony_id is required")
    if len(ceremony_ids) > 200:
        raise HTTPException(status_code=400, detail="Max 200 ceremonies per batch")

    # Fetch ceremonies + ensure certs exist
    fetched = []
    failed = []
    pdfs = []  # list of (ceremony_dict, pdf_bytes, sha256)
    for cid in ceremony_ids:
        ceremony = await db.ceremonies.find_one(
            {"ceremony_id": cid},
            {"_id": 0, "ceremony_id": 1, "document_name": 1, "signer_name": 1,
             "initiated_by": 1, "created_at": 1, "status": 1,
             "consensus.result": 1, "blockchain_seal.transaction_id": 1},
        )
        if not ceremony:
            failed.append({"ceremony_id": cid, "reason": "not_found"})
            continue
        if ceremony.get("status") != "sealed":
            failed.append({"ceremony_id": cid, "reason": "not_sealed"})
            continue
        cert = await _ensure_certificate(cid)
        if not cert:
            failed.append({"ceremony_id": cid, "reason": "cert_generation_failed"})
            continue
        pdf_bytes = base64.b64decode(cert["pdf_base64"])
        sha = hashlib.sha256(pdf_bytes).hexdigest()
        fetched.append(ceremony)
        pdfs.append((ceremony, pdf_bytes, sha))

    if not pdfs:
        raise HTTPException(status_code=400, detail={"message": "No eligible ceremonies", "failed": failed})

    batch_id = "BATCH-" + datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S") + "-" + hashlib.sha1(
        ("".join(ceremony_ids)).encode()).hexdigest()[:8].upper()

    # Build cover PDF
    items_for_cover = [{
        "ceremony_id": c.get("ceremony_id"),
        "document_name": c.get("document_name", ""),
        "signer_name": c.get("signer_name", ""),
        "created_at": c.get("created_at", ""),
    } for c, _, _ in pdfs]
    cover_pdf = _build_cover_pdf(items_for_cover, batch_id, current_user.email)

    # Build combined PDF (cover + all certs) using pypdf if available, else fall back to ZIP-only
    combined_bytes = None
    try:
        try:
            from pypdf import PdfWriter, PdfReader  # type: ignore
        except ImportError:
            from PyPDF2 import PdfWriter, PdfReader  # type: ignore
        writer = PdfWriter()
        for reader_src in [cover_pdf] + [p for _, p, _ in pdfs]:
            r = PdfReader(io.BytesIO(reader_src))
            for page in r.pages:
                writer.add_page(page)
        out = io.BytesIO()
        writer.write(out)
        combined_bytes = out.getvalue()
    except Exception as e:
        logger.warning(f"Combined PDF generation failed: {e}")
        combined_bytes = None  # ZIP will skip the combined file

    # Build manifest CSV
    csv_buf = io.StringIO()
    w = csv.writer(csv_buf)
    w.writerow(["#", "ceremony_id", "document_name", "signer_name", "initiated_by",
                "created_at", "consensus_result", "hedera_tx", "filename", "sha256",
                "size_bytes"])
    file_entries = []
    for i, (c, pdf, sha) in enumerate(pdfs, start=1):
        fname = f"certificates/{_safe_filename(c.get('document_name', 'cert'))}_{(c.get('ceremony_id') or '')[:12]}.pdf"
        file_entries.append((fname, pdf, sha))
        w.writerow([
            i, c.get("ceremony_id", ""), c.get("document_name", ""),
            c.get("signer_name", ""), c.get("initiated_by", ""),
            c.get("created_at", ""), (c.get("consensus") or {}).get("result", ""),
            (c.get("blockchain_seal") or {}).get("transaction_id", "") or "",
            fname, sha, len(pdf),
        ])
    manifest_csv = csv_buf.getvalue().encode()

    # Plain-text manifest
    txt = io.StringIO()
    txt.write("NotaryChain Batch Certificate Bundle\n")
    txt.write(f"Batch ID:       {batch_id}\n")
    txt.write(f"Generated:      {datetime.now(timezone.utc).isoformat()}\n")
    txt.write(f"Generated by:   {current_user.email}\n")
    txt.write(f"Certificates:   {len(pdfs)}\n")
    txt.write(f"Failed:         {len(failed)}\n")
    if failed:
        txt.write("\nFailed items:\n")
        for f in failed:
            txt.write(f"  - {f['ceremony_id']}: {f['reason']}\n")
    txt.write("\nEach certificate is a self-contained, verifiable PDF.\n")
    manifest_txt = txt.getvalue().encode()

    # Assemble ZIP
    zip_buf = io.BytesIO()
    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname, pdf, _sha in file_entries:
            zf.writestr(fname, pdf)
        if combined_bytes:
            zf.writestr("combined_certificates.pdf", combined_bytes)
        zf.writestr("manifest.csv", manifest_csv)
        zf.writestr("MANIFEST.txt", manifest_txt)
        # Cover as standalone too
        zf.writestr("cover.pdf", cover_pdf)
    zip_bytes = zip_buf.getvalue()

    # Audit log
    try:
        import uuid as _u
        await db.audit_logs.insert_one({
            "id": _u.uuid4().hex,
            "user_id": getattr(current_user, "id", None),
            "user_email": current_user.email,
            "action": "batch_certificate_export",
            "resource_type": "ceremony_certificate",
            "description": f"Generated batch of {len(pdfs)} certificates ({batch_id})",
            "details": {"batch_id": batch_id, "count": len(pdfs), "failed_count": len(failed)},
            "severity": "info",
            "timestamp": datetime.now(timezone.utc).isoformat(),
        })
    except Exception:
        pass

    filename = f"{batch_id}.zip"
    return Response(
        content=zip_bytes,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{filename}"',
            "X-Batch-Id": batch_id,
            "X-Batch-Count": str(len(pdfs)),
            "X-Batch-Failed": str(len(failed)),
        },
    )
