import React from 'react';
import { FileText, BookOpen, PenTool, CheckCircle } from 'lucide-react';
import { Card, CardContent } from './ui/card';

const aiFeatures = [
  {
    icon: FileText,
    title: 'AI Generator',
    description: 'Create contracts or agreements from a simple description or video interview.',
  },
  {
    icon: BookOpen,
    title: 'AI Summarizer',
    description: 'Get instant summaries and keyword extractions from any document.',
  },
  {
    icon: PenTool,
    title: 'AI Smart Fill™',
    description: 'Fill out templates or correct errors on the fly using plain English.',
  },
  {
    icon: CheckCircle,
    title: 'AI Remediator',
    description:
      'Automatically suggests missing legal clauses and corrections to strengthen your documents.',
  },
];

const AIDocumentSection = () => {
  return (
    <section className="py-24 bg-gradient-to-br from-[#0f1825] via-[#1a2332] to-[#0f1825]">
      <div className="max-w-7xl mx-auto px-6">
        <div className="mb-12">
          <div className="inline-block px-4 py-2 bg-blue-500/10 rounded-full border border-blue-500/30 mb-4">
            <span className="text-blue-400 font-semibold">AI Document Suite™</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
            From Generation to Remediation, Instantly.
          </h2>
          <p className="text-gray-400 text-lg max-w-3xl">
            NotaryChain's™ AI is more than an analyst—it's your co-pilot. Draft, summarize,
            fill, and correct documents with simple, natural language commands, turning hours
            of work into minutes.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {aiFeatures.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Card
                key={index}
                className="bg-[#1a2332]/50 border border-gray-800 hover:border-blue-500/50 transition-all duration-300 group"
              >
                <CardContent className="p-6">
                  <Icon className="w-8 h-8 text-blue-500 mb-4 group-hover:scale-110 transition-transform" />
                  <h4 className="text-lg font-semibold text-white mb-2">{feature.title}</h4>
                  <p className="text-gray-400 text-sm leading-relaxed">{feature.description}</p>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* AI Document Generator Demo */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center">
          <div>
            <h3 className="text-2xl font-bold text-white mb-4">AI Document Generator</h3>
            <p className="text-gray-400 mb-6">Describe the document you need.</p>
            <div className="bg-[#0a0f1a] border border-gray-800 rounded-lg p-6">
              <p className="text-gray-300 leading-relaxed">
                "A bill of sale for my 2023 Tesla Model Y, VIN 5YJSA1E, to Alex Smith for
                $45,000. Sale date is today in Miami, FL. The vehicle is sold as-is."
              </p>
            </div>
          </div>
          <div>
            <div className="bg-white rounded-lg p-8 shadow-2xl">
              <h4 className="text-2xl font-bold text-gray-900 mb-4">BILL OF SALE</h4>
              <div className="space-y-3 text-gray-700 text-sm leading-relaxed">
                <p>
                  This Bill of Sale is made on [Date], by and between [Seller Name] ("Seller")
                  and Alex Smith ("Buyer").
                </p>
                <p>
                  Seller agrees to sell to Buyer the 2023 Tesla Model Y, VIN 5YJSA1E...
                </p>
                <div className="pt-4 border-t border-gray-200">
                  <p className="text-xs text-gray-500">Generated by AI Document Suite™</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default AIDocumentSection;