import React from 'react';
import { Scale, Shield, FileCheck, Award } from 'lucide-react';
import { Card, CardContent } from './ui/card';

const complianceItems = [
  {
    icon: FileCheck,
    title: 'ESIGN Act (2000) & UETA',
    description:
      'Electronic signatures have the same legal weight as wet ink signatures under federal law.',
    status: 'Fully Compliant',
  },
  {
    icon: Scale,
    title: 'RULONA Standards',
    description:
      'Revised Uniform Law on Notarial Acts specifically calls for "tamper-evident" technology. Blockchain is the ultimate example.',
    status: 'Certified',
  },
  {
    icon: Shield,
    title: 'Federal Rules of Evidence',
    description:
      'Rules 902(13) & 902(14) allow "Certified Records Generated by an Electronic Process" to be self-authenticating.',
    status: 'Court Admissible',
  },
  {
    icon: Award,
    title: 'RON Compliance - All 50 States',
    description:
      'The SECURE Notarization Act establishes national standards. Remote Online Notarization (RON) is now recognized nationwide.',
    status: 'Nationwide Coverage',
  },
];

const LegalComplianceSection = () => {
  return (
    <section className="py-24 bg-gradient-to-br from-[#0f1825] via-white to-cream-100">
      <div className="max-w-7xl mx-auto px-6">
        <div className="text-center mb-16">
          <div className="inline-block px-4 py-2 bg-green-500/10 rounded-full border border-green-500/30 mb-4">
            <span className="text-green-400 font-semibold">Court-Approved Technology</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Built on Legal Foundations You Can Trust
          </h2>
          <p className="text-slate-500 text-lg max-w-3xl mx-auto">
            Our blockchain notarization is backed by federal law and recognized across all 50
            states, giving you the strongest legal protection available.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-12">
          {complianceItems.map((item, index) => {
            const Icon = item.icon;
            return (
              <Card
                key={index}
                className="bg-white border border-slate-200 hover:border-green-500/50 transition-all duration-300 group"
              >
                <CardContent className="p-6">
                  <div className="flex items-start gap-4">
                    <div className="flex-shrink-0">
                      <div className="w-12 h-12 bg-green-500/10 rounded-lg flex items-center justify-center group-hover:bg-green-500/20 transition-colors">
                        <Icon className="w-6 h-6 text-green-400" />
                      </div>
                    </div>
                    <div className="flex-1">
                      <div className="flex items-start justify-between mb-2">
                        <h3 className="text-lg font-semibold text-white">{item.title}</h3>
                        <span className="text-xs bg-green-500/20 text-green-400 px-2 py-1 rounded-full border border-green-500/30 flex-shrink-0 ml-2">
                          {item.status}
                        </span>
                      </div>
                      <p className="text-slate-500 text-sm leading-relaxed">{item.description}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>

        {/* Legal Defense Advantage */}
        <div className="bg-gradient-to-r from-green-600/10 to-blue-600/10 border border-green-500/30 rounded-2xl p-8">
          <div className="flex flex-col md:flex-row items-center gap-8">
            <div className="flex-shrink-0">
              <div className="w-20 h-20 bg-green-500/20 rounded-full flex items-center justify-center">
                <Shield className="w-10 h-10 text-green-400" />
              </div>
            </div>
            <div className="flex-1 text-center md:text-left">
              <h3 className="text-2xl font-bold text-white mb-3">
                The Ultimate Legal Defense
              </h3>
              <p className="text-slate-500 leading-relaxed">
                Instead of <span className="text-white font-semibold">you proving</span> the
                document is real, the accuser has the{' '}
                <span className="text-white font-semibold">impossible task</span> of proving the
                global blockchain was hacked. You are defending from the strongest possible
                position.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default LegalComplianceSection;